
version: '3.7'
services:
  backend:
    build: ./Server/
    ports:
      - "5000:5000"
    volumes:
      - ./ultimate_watchlist_backend:/usr/src/app
  frontend:
    build: ./Client/
    ports:
      - "3000:3000"
    volumes:
      - ./ultimate_watchlist_frontend:/usr/src/app
    depends_on:
      - backend
