version: "3.7"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3100:80"
  backend:
    build:
      context: ./Server
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./Server:/app
  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
      - ./Client:/app
    # depends_on:
    #   - nginx
